//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFormBoletaGarantia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inmobiliaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inmobiliaria()
        {
            this.UsuarioInmobiliaria = new HashSet<UsuarioInmobiliaria>();
            this.BoletaGarantia = new HashSet<BoletaGarantia>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Rut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioInmobiliaria> UsuarioInmobiliaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoletaGarantia> BoletaGarantia { get; set; }
    }
}
